config/routes.rb
Squid::Application.routes.draw do

  devise_for :admins, :skip => :registration
  devise_for :investors
  devise_for :users

  root to:'public#index'
  get '/dashboard' => 'dashboard#index'

  resources :information
  resources :user, except: [:new, :create]
  resources :investor, except: [:new, :create]
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/information.rb
class Information < ActiveRecord::Base
end

app/models/investor.rb
class Investor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_actor
    if current_admin
      authenticate_admin!
    elsif current_investor
      authenticate_investor!
    else
      authenticate_user!
    end
  end

  def after_sign_in_path_for(resource_name)
    dashboard_path
  end

  def after_sign_out_path_for(resource_name)
    case resource_name
    when :admin
      new_admin_session_path
    when :investor
      new_investor_session_path
    when :user
      new_user_session_path
    else
      root_path
    end
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  #before_filter :authenticate_user!
  before_filter :authenticate_actor

  layout "dashboard"

  def index
    @informations = Information.all(order: 'created_at desc', limit: 5)
  end

end

app/controllers/information_controller.rb
class InformationController < DashboardController
  before_filter :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_information, only: [:show, :edit, :update, :destroy]

  # GET /information
  # GET /information.json
  def index
    @information = Information.all(:order => 'created_at desc')
  end

  # GET /information/1
  # GET /information/1.json
  def show
  end

  # GET /information/new
  def new
    @information = Information.new
  end

  # GET /information/1/edit
  def edit
  end

  # POST /information
  # POST /information.json
  def create
    @information = Information.new(information_params)

    respond_to do |format|
      if @information.save
        format.html { redirect_to @information, notice: 'Information was successfully created.' }
        format.json { render action: 'show', status: :created, location: @information }
      else
        format.html { render action: 'new' }
        format.json { render json: @information.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /information/1
  # PATCH/PUT /information/1.json
  def update
    respond_to do |format|
      if @information.update(information_params)
        format.html { redirect_to @information, notice: 'Information was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @information.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /information/1
  # DELETE /information/1.json
  def destroy
    @information.destroy
    respond_to do |format|
      format.html { redirect_to information_index_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_information
      @information = Information.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def information_params
      params.require(:information).permit(:title)
    end
end

app/controllers/investors.old/registrations_controller.rb
class Investors::RegistrationsController < Devise::RegistrationsController
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
end

app/controllers/user_controller.rb
class UserController < DashboardController
  before_filter :authenticate_user!, only: [:edit, :update, :destroy]
  before_filter :authenticate_admin!, only: [:index]
  before_filter :authenticate_investor!, only: [:index]

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @user = User.all(:order => 'created_at desc')
  end

  def show
    if current_user && @user.id != current_user.id
      redirect_to dashboard_path
      #raise 'Hitonoha mirenaiyo! Exception'
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        current_user = @user
        format.html { redirect_to @user, notice: 'user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to user_index_url }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit([:sei, :mei])
    end
end

app/helpers/application_helper.rb
#coding: utf-8
module ApplicationHelper

  def resource_name_to_title(resource_name)
    case resource_name
    when :admin
      '管理者'
    when :investor
      '企業'
    else
      '起業家'
    end
  end

  def current_actor
    if current_admin
      current_admin
    elsif current_investor
      current_investor
    elsif current_user
      current_user
    end
  end

  def current_actor_name
    current_actor.class.to_s.downcase
  end

end

app/helpers/information_helper.rb
module InformationHelper
end

app/views/dashboard/index.html.erb
<%= render partial: '/information/headline', locals: {informations: @informations} %>

app/views/information/_form.html.erb
<%= form_for(@information, html: {class: 'form-horizontal'}) do |f| %>
  <% if @information.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@information.errors.count, "error") %> prohibited this information from being saved:</h2>

      <ul>
      <% @information.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title, class:"control-label" %>
    <div class="controls">
      <%= f.text_field :title, :autofocus => true, id:"inputTitle", placeholder:"Title" %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/information/_headline.html.erb
<div class="span10 alert alert-information">
  <h3>新着お知らせ</h3>
  <% informations.each do |i| %>
    <ul class="inline">
      <li><%= i.created_at.strftime("%Y/%m/%d %H:%M") %></li>
      <li><%= link_to i.title, i %></li>
    </ul>
  <% end %>
  <p class="pull-right"><%= link_to "もっと見る", information_index_path %></p>
</div>

app/views/information/edit.html.erb
<h3>お知らせの編集</h3>

<%= render 'form' %>

<%= link_to '詳細', @information %>

app/views/information/index.html.erb
<h3>お知らせ一覧</h3>

<table class="table table-striped">
  <thead>
    <tr>
      <th>作成日</th>
      <th>件名</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @information.each do |information| %>
    <tr>
      <td><%= information.created_at.strftime("%Y/%m/%d %H:%M") %></td>
      <td><%= link_to information.title, information %></td>
      <td><%= link_to 'Edit', edit_information_path(information) if current_admin %> <%= link_to 'Destroy', information, method: :delete, data: { confirm: 'Are you sure?' } if current_admin %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'お知らせ作成', new_information_path if current_admin %>

app/views/information/new.html.erb
<h3>お知らせ作成</h3>

<%= render 'form' %>

<%= link_to '戻る', information_index_path %>

app/views/information/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @information.title %>
</p>


<%= link_to '編集', edit_information_path(@information) if current_admin %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Squid" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%#= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
    <%#= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>
    <%#= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>
    <%#= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>
    <%#= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Squid</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Squid" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%#= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
    <%#= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>
    <%#= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>
    <%#= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>
    <%#= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Squid</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Home", dashboard_path  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
            <div class="pull-right">
              <%= link_to("Logout", self.send("destroy_#{current_actor_name}_session_path"), method:'delete', class:'btn') if (current_actor) %>
            </div>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <%= render partial:"/shared/submenu/user" if current_user %>
          <%= render partial:"/shared/submenu/investor" if current_investor %>
          <%= render partial:"/shared/submenu/admin" if current_admin %>
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Squid" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%#= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
    <%#= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>
    <%#= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>
    <%#= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>
    <%#= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Squid</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
            <div class="pull-right">
              <%= link_to("Logout", destroy_user_session_path, method:'delete', class:'btn') if (current_user || current_investor) %>
            </div>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <%= render partial:"/shares/submenu/user" if current_user %>
          <%= render partial:"/shares/submenu/investor" if current_investor %>
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/shared/submenu/_admin.html.erb
<div class="well sidebar-nav">
  <ul class="nav nav-list">
    <li class="nav-header">管理者メニュー</li>
    <li><%= link_to "お知らせ管理", information_index_path  %></li>
    <li><%= link_to "Link2", "/path2"  %></li>
    <li><%= link_to "Link3", "/path3"  %></li>
  </ul>
</div>

app/views/shared/submenu/_investor.html.erb
<div class="well sidebar-nav">
  <ul class="nav nav-list">
    <li class="nav-header">企業メニュー</li>
    <li><%= link_to "お知らせ一覧", information_index_path  %></li>
    <li><%= link_to "Link2", "/path2"  %></li>
    <li><%= link_to "Link3", "/path3"  %></li>
  </ul>
</div>

app/views/shared/submenu/_user.html.erb
<div class="well sidebar-nav">
  <ul class="nav nav-list">
    <li class="nav-header">起業家メニュー</li>
    <li><%= link_to "お知らせ一覧", information_index_path  %></li>
    <li><%= link_to "登録情報管理", edit_user_path(current_user)  %></li>
    <li><%= link_to "Link3", "/path3"  %></li>
  </ul>
</div>

app/views/user/_form.html.erb
<%= form_for(@user, html: {class: 'form-horizontal'}) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :sei, class:"control-label" %>
    <div class="controls">
      <%= f.text_field :sei, :autofocus => true, id:"inputSei", placeholder:"名字" %>
      <%= f.text_field :mei, id:"inputMei", placeholder:"名前" %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/user/edit.html.erb
<h3>登録情報の編集</h3>

<%= render 'form' %>

<%= link_to '詳細', current_user %>

app/views/user/index.html.erb
<h3>お知らせ一覧</h3>

<table class="table table-striped">
  <thead>
    <tr>
      <th>作成日</th>
      <th>件名</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user.each do |user| %>
    <tr>
      <td><%= user.created_at.strftime("%Y/%m/%d %H:%M") %></td>
      <td><%= link_to user.title, user %></td>
      <td><%= link_to 'Edit', edit_user_path(user) if current_admin %> <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } if current_admin %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'お知らせ作成', new_user_path if current_admin %>

app/views/user/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>氏名:</strong>
  <%= @user.sei %> <%= @user.mei %>
</p>


<%= link_to '編集', edit_user_path(current_user) if current_user %>